# Generated by Django 3.1.11 on 2021-06-13 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentpage',
            old_name='body',
            new_name='tournament_information',
        ),
        migrations.AddField(
            model_name='tournamentpage',
            name='tournament_packet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
