# Generated by Django 3.1.11 on 2021-06-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20210613_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentpage',
            name='year',
        ),
    ]
