# Generated by Django 3.1.11 on 2021-06-13 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('tournament', '0003_remove_tournamentpage_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tournamentPage',
        ),
    ]
