version: "3.7"

services: 
  
  mhac_admin:
    build:
      context: ../mhac_admin
      dockerfile: Dockerfile
    depends_on:
      - postgres
    #   - mhac_api
    ports:
      - "8001:8001"
  
  postgres:
    image: postgres:11.5-alpine
    # container_name: "mhac_db"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
    
