# Generated by Django 3.1.8 on 2021-05-15 16:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('generic_page', '0002_auto_20210505_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericpage',
            name='body',
        ),
        migrations.AddField(
            model_name='genericpage',
            name='content',
            field=wagtail.core.fields.StreamField([('image_and_text', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(Required=True, help_text='Your content goes here'))]))], blank=True, null=True),
        ),
    ]
