# Generated by Django 3.1.11 on 2021-09-13 03:55

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('generic_page', '0010_auto_20210912_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='content',
            field=wagtail.core.fields.StreamField([('team_image_block', wagtail.core.blocks.StructBlock([('logo', wagtail.images.blocks.ImageChooserBlock(Required=True))])), ('page_content', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock(blank=True, form_classname='Section Header', required=False)), ('displayHeader', wagtail.core.blocks.BooleanBlock(required=False)), ('content', wagtail.core.blocks.RichTextBlock(Required=True, help_text='Add the page content here'))])), ('content_image', wagtail.core.blocks.StructBlock([('year', wagtail.core.blocks.ChoiceBlock(choices=[b'[{"level":"18U Boys","season_name":"2020-2021 Fall","season_start_date":"2020-11-01T00:00:00","roster_submission_deadline":"2020', b'-11-01T00:00:00","tournament_start_date":"2021-02-15T00:00:00","sport":"Basketball","year":"2020","slug":"2020_18u_boys_basketba', b'll"},{"level":"18U Girls","season_name":"2020-2021 Fall","season_start_date":"2020-11-01T00:00:00","roster_submission_deadline":', b'"2020-11-01T00:00:00","tournament_start_date":"2021-02-15T00:00:00","sport":"Basketball","year":"2020","slug":"2020_18u_girls_ba', b'sketball"},{"level":"16U Boys","season_name":"2020-2021 Fall","season_start_date":"2020-11-01T00:00:00","roster_submission_deadl', b'ine":"2020-11-01T00:00:00","tournament_start_date":"2021-02-15T00:00:00","sport":"Basketball","year":"2020","slug":"2020_16u_boy', b's_basketball"},{"level":"14U Boys","season_name":"2020-2021 Fall","season_start_date":"2020-11-01T00:00:00","roster_submission_d', b'eadline":"2020-11-01T00:00:00","tournament_start_date":"2021-02-15T00:00:00","sport":"Basketball","year":"2020","slug":"2020_14u', b'_boys_basketball"}]'])), ('image', wagtail.images.blocks.ImageChooserBlock(Required=True)), ('image_location', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')]))]))], blank=True, null=True),
        ),
    ]
