# Generated by Django 3.1.11 on 2021-09-13 04:19

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('generic_page', '0012_auto_20210913_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='content',
            field=wagtail.core.fields.StreamField([('team_image_block', wagtail.core.blocks.StructBlock([('logo', wagtail.images.blocks.ImageChooserBlock(Required=True))])), ('page_content', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock(blank=True, form_classname='Section Header', required=False)), ('displayHeader', wagtail.core.blocks.BooleanBlock(required=False)), ('content', wagtail.core.blocks.RichTextBlock(Required=True, help_text='Add the page content here'))])), ('content_image', wagtail.core.blocks.StructBlock([('year', wagtail.core.blocks.ChoiceBlock(choices=[('780e5f03-910e-4fa6-962c-0dedad878104', '2021-2020 Fall 18U Boys'), ('be2dca72-ef63-44c0-96fa-6b65bdab9b63', '2020-2021 Fall 18U Boys'), ('3323edf0-d806-4e32-9fd2-cb698a27b3a9', '2019-2020 Fall 18U Boys'), ('f2b71dae-b164-44a1-bfb5-abde8261fb1f', '2020-2021 Fall 18U Girls'), ('d099d7a6-05ff-4028-88a4-e609ddbb8d26', '2019-2020 Fall 18U Girls'), ('5412114d-1df5-4f1d-ac07-ef400f76bd0f', '2020-2021 Fall 16U Boys'), ('c300cc68-e990-4158-a7c5-9a15c9f27f70', '2019-2020 Fall 16U Boys'), ('d7dc6e4a-c495-4580-a793-5aa252552285', '2020-2021 Fall 14U Boys'), ('ff4014db-cb89-4e45-b4ea-8521b301c176', '2019-2020 Fall 14U Boys')])), ('image', wagtail.images.blocks.ImageChooserBlock(Required=True)), ('image_location', wagtail.core.blocks.ChoiceBlock(choices=[('content-left', 'Left'), ('content-center', 'Center'), ('content-right', 'Right')]))]))], blank=True, null=True),
        ),
    ]
