# Generated by Django 4.1.4 on 2022-12-28 22:56

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("generic_page", "0015_auto_20211015_2016"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "team_image_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "logo",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        Required=True
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "page_content",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "header",
                                    wagtail.blocks.CharBlock(
                                        blank=True,
                                        form_classname="Section Header",
                                        required=False,
                                    ),
                                ),
                                (
                                    "displayHeader",
                                    wagtail.blocks.BooleanBlock(required=False),
                                ),
                                (
                                    "content",
                                    wagtail.blocks.RichTextBlock(
                                        Required=True,
                                        help_text="Add the page content here",
                                    ),
                                ),
                                (
                                    "isHeaderLink",
                                    wagtail.blocks.BooleanBlock(
                                        form_classname="Is Header a Link",
                                        required=False,
                                    ),
                                ),
                                ("headerLink", wagtail.blocks.URLBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        "content_image",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "year",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            {
                                                "level": {"id": "", "name": ""},
                                                "season_id": "",
                                                "season_name": "",
                                            }
                                        ]
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        Required=True
                                    ),
                                ),
                                (
                                    "image_location",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("content-left", "Left"),
                                            ("content-center", "Center"),
                                            ("content-right", "Right"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
