# Generated by Django 4.1.11 on 2023-10-02 03:15

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('generic_page', '0016_alter_genericpage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericpage',
            name='content',
        ),
        migrations.CreateModel(
            name='ChampionPageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('content', wagtail.fields.StreamField([('team_image_block', wagtail.blocks.StructBlock([('logo', wagtail.images.blocks.ImageChooserBlock(Required=True))])), ('page_content', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(blank=True, form_classname='Section Header', required=False)), ('displayHeader', wagtail.blocks.BooleanBlock(required=False)), ('content', wagtail.blocks.RichTextBlock(Required=True, help_text='Add the page content here')), ('isHeaderLink', wagtail.blocks.BooleanBlock(form_classname='Is Header a Link', required=False)), ('headerLink', wagtail.blocks.URLBlock(required=False))])), ('content_image', wagtail.blocks.StructBlock([('year', wagtail.blocks.ChoiceBlock(choices=[{'level': {'id': '', 'name': ''}, 'season_id': '', 'season_name': ''}])), ('image', wagtail.images.blocks.ImageChooserBlock(Required=True)), ('image_location', wagtail.blocks.ChoiceBlock(choices=[('content-left', 'Left'), ('content-center', 'Center'), ('content-right', 'Right')]))]))], blank=True, null=True, use_json_field=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='champs', to='generic_page.genericpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
