# Generated by Django 4.1.11 on 2023-10-02 03:18

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('generic_page', '0017_remove_genericpage_content_championpagecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championpagecontent',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='champsList', to='generic_page.genericpage'),
        ),
    ]
