# Generated by Django 4.1.11 on 2023-10-02 03:26

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('generic_page', '0018_alter_championpagecontent_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championpagecontent',
            name='content',
            field=wagtail.fields.StreamField([('team_image_block', wagtail.blocks.StructBlock([('logo', wagtail.images.blocks.ImageChooserBlock(Required=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
