# Generated by Django 4.1.11 on 2023-10-02 03:30

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('generic_page', '0019_alter_championpagecontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championpagecontent',
            name='content',
            field=wagtail.fields.StreamField([('team_image_block', wagtail.blocks.StructBlock([('logo', wagtail.images.blocks.ImageChooserBlock(Required=True))])), ('content_image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(Required=True)), ('image_location', wagtail.blocks.ChoiceBlock(choices=[('content-left', 'Left'), ('content-center', 'Center'), ('content-right', 'Right')]))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
