# Generated by Django 3.1.11 on 2021-06-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210505_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='tagline_line1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tagline_line2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
