# Generated by Django 3.1.11 on 2021-09-25 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0007_homepagecarouselorderables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecarouselorderables',
            name='carousel_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
