# Generated by Django 3.1.11 on 2021-10-15 02:35

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210925_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_image',
        ),
        migrations.AlterField(
            model_name='homepagecarouselorderables',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_image', to='home.homepage'),
        ),
    ]
