# Generated by Django 3.1.11 on 2021-06-12 04:45

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail_headless_preview.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutStreamFields',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.core.fields.StreamField([('about_paragraph', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(Required=True, help_text='Add the page content here'))]))])),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_headless_preview.models.HeadlessPreviewMixin, 'wagtailcore.page'),
        ),
    ]
