# Generated by Django 3.1.11 on 2021-06-12 04:50

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutstreamfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutstreamfields',
            name='content',
            field=wagtail.core.fields.StreamField([('about_paragraph', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock(form_classname='Section Header')), ('text', wagtail.core.blocks.RichTextBlock(Required=True, help_text='Add the page content here'))]))]),
        ),
    ]
