# Generated by Django 3.1.11 on 2021-06-12 05:08

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20210612_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutstreamfields',
            name='content',
            field=wagtail.core.fields.StreamField([('about_paragraph', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock(blank=True, form_classname='Section Header', required=False)), ('text', wagtail.core.blocks.RichTextBlock(Required=True, help_text='Add the page content here'))]))]),
        ),
    ]
