# Generated by Django 3.1.11 on 2021-06-13 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtaildocs', '0012_uploadeddocument'),
        ('about', '0006_auto_20210612_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutstreamfields',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
    ]
