# Generated by Django 3.1.11 on 2021-06-13 05:55

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_auto_20210613_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutstreamfields',
            name='content',
            field=wagtail.core.fields.StreamField([('about_paragraph', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock(blank=True, form_classname='Section Header', required=False)), ('displayHeader', wagtail.core.blocks.BooleanBlock(required=False)), ('section', wagtail.core.blocks.CharBlock(required=False)), ('content', wagtail.core.blocks.RichTextBlock(Required=True, help_text='Add the page content here'))])), ('document', wagtail.core.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock(required=False))]))], blank=True, null=True),
        ),
    ]
