# Generated by Django 3.1.11 on 2021-06-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_contentorderable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentorderable',
            name='page',
        ),
    ]
