# Generated by Django 3.1.11 on 2021-06-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_auto_20210620_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentorderable',
            name='content',
        ),
    ]
