# Generated by Django 3.1.11 on 2021-06-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0018_aboutpagecontent_displaysectiontitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='displaySectionTitle',
            field=models.BooleanField(default=True),
        ),
    ]
