# Generated by Django 3.1.11 on 2021-06-28 23:34

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0019_auto_20210620_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='about.aboutstreamfields'),
        ),
    ]
