# Generated by Django 3.1.11 on 2021-07-28 14:31

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0020_auto_20210627_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='subsections',
            field=wagtail.core.fields.StreamField([('about_paragraph', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock(blank=True, form_classname='Section Header', required=False)), ('displayHeader', wagtail.core.blocks.BooleanBlock(required=False)), ('content', wagtail.core.blocks.RichTextBlock(Required=True, help_text='Add the page content here'))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
