# Generated by Django 3.1.11 on 2021-09-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0022_contentimagelistpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentimagelistpage',
            name='year',
            field=models.CharField(default=2019, max_length=4),
            preserve_default=False,
        ),
    ]
