# Generated by Django 3.1.11 on 2021-09-12 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('about', '0024_contentimagelistpage_content_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentImageListPage',
        ),
    ]
