# Generated by Django 3.1.11 on 2021-10-15 20:16

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0026_auto_20211015_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='subsections',
            field=wagtail.core.fields.StreamField([('about_paragraph', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock(blank=True, form_classname='Section Header', required=False)), ('displayHeader', wagtail.core.blocks.BooleanBlock(required=False)), ('content', wagtail.core.blocks.RichTextBlock(Required=True, help_text='Add the page content here')), ('isHeaderLink', wagtail.core.blocks.BooleanBlock(form_classname='Is Header a Link', required=False)), ('headerLink', wagtail.core.blocks.URLBlock(required=False))])), ('table_block', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock(blank=True, form_classname='Section Header', required=False)), ('displayHeader', wagtail.core.blocks.BooleanBlock(required=False)), ('isHeaderLink', wagtail.core.blocks.BooleanBlock(form_classname='Is Header a Link', required=False)), ('headerLink', wagtail.core.blocks.URLBlock(required=False)), ('content', wagtail.contrib.table_block.blocks.TableBlock())]))], blank=True, null=True),
        ),
    ]
