# Generated by Django 4.1.4 on 2022-12-28 22:56

from django.db import migrations
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0027_auto_20211015_2016"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpagecontent",
            name="subsections",
            field=wagtail.fields.StreamField(
                [
                    (
                        "about_paragraph",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "header",
                                    wagtail.blocks.CharBlock(
                                        blank=True,
                                        form_classname="Section Header",
                                        required=False,
                                    ),
                                ),
                                (
                                    "displayHeader",
                                    wagtail.blocks.BooleanBlock(required=False),
                                ),
                                (
                                    "content",
                                    wagtail.blocks.RichTextBlock(
                                        Required=True,
                                        help_text="Add the page content here",
                                    ),
                                ),
                                (
                                    "isHeaderLink",
                                    wagtail.blocks.BooleanBlock(
                                        form_classname="Is Header a Link",
                                        required=False,
                                    ),
                                ),
                                ("headerLink", wagtail.blocks.URLBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        "table_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "header",
                                    wagtail.blocks.CharBlock(
                                        blank=True,
                                        form_classname="Section Header",
                                        required=False,
                                    ),
                                ),
                                (
                                    "displayHeader",
                                    wagtail.blocks.BooleanBlock(required=False),
                                ),
                                (
                                    "isHeaderLink",
                                    wagtail.blocks.BooleanBlock(
                                        form_classname="Is Header a Link",
                                        required=False,
                                    ),
                                ),
                                ("headerLink", wagtail.blocks.URLBlock(required=False)),
                                (
                                    "content",
                                    wagtail.contrib.table_block.blocks.TableBlock(),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
